input: './data/input.mp4'
output: './output/output.mp4'
mask_output: './output/mask.mp4'

preprocess:
    preprocess_gray:
        blur_gray:
            kernel_size: 5

    preprocess_color:
        denoise_color:
            h: 10
            h_color: 10
            template_window_size: 7
            search_window_size: 21

motion_detector:
    history_frames: 9

    registration:
        good_match_percent: 0.27
        ransac_max_error: 4.96
        ssc_num_ret_points: 10001
        ssc_tolerence: 0.13

    quantize_frames:
        scale_factor: 30

    noise_reduction:
        erode_kernel_size: 6
        dilate_kernel_size: 24
        combine_kernel_size: 14

    hysteresis:
        required_motion_observations: 1
        required_no_motion_observations: 4

    group_filter:
        size: 1

    min_size_filter:
        min_size: 5

dead_reckoning:
    dist_threshold: 30
    same_region_threshold: 0.3

motion_detector_stages:
    HysteresisFilter:
        order: 0
        enabled: 0
    GroupFilter:
        order: 1
        enabled: 0
    DilateErodeFilter:
        order: 2
        enabled: 1

# preprocess_stages:

