[tool.poetry]
name = "baboon-tracking"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
numpy = "^1.19.0"
opencv-python = "^4.2.0.34"
opencv-contrib-python = "^4.2.0.34"
tqdm = "^4.62.3"
pyAesCrypt = "^6.0.0"
colorama = "^0.4.4"
Rx = "^3.2.0"
Sphinx = "^4.3.0"
pandas = "^1.3.4"
scikit-image = "^0.18.3"
pytest = "^6.2.5"
matplotlib = "^3.5.0"
google-api-python-client = "^2.31.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.6"
firebase-admin = "^5.1.0"
numba = "^0.54.1"
Pillow = "^8.4.0"
PyYAML = "^6.0"
scikit-learn = "^1.0.2"
GitPython = "^3.1.27"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
black = "^21.11b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
